@echo off

setx POSTGRES_USERNAME "KENDI_KULLANICI_ADINI_YAZ"
setx POSTGRES_PASSWORD "KENDI_PAROLANI_YAZ"

setx JAVA_SECRETKEY "KENDI_JWT_SECRRET_ANAHTARINI_YAZ"
setx JAVA_ISSUER "KENDI_JWT_ISSUER_YAZ"

setx GIT_MICROSERVICE_PROJECT "https://github.com/USERNAME/PROJE_ADI.git"
setx GIT_USERNAME "GITHUB_KULLANICI_ADINI_YAZ"
setx GIT_TOKEN_KEY "GITHUB_TOKEN_DEGERINI_YAZ"