@echo off

setx POSTGRES_USERNAME "POSTGRES_USERNAME_VALUE"
setx POSTGRES_PASSWORD "POSTGRES_PASSWORD_VALUE"

setx JAVA_SECRETKEY "JWT_SECRETKEY_VALUE"
setx JAVA_ISSUER "JWT_ISSUER_VALUE"

setx GIT_CONFIG_PROJECT "https://github.com/USERNAME/CONFIG_PROJECT_NAME.git"
setx GIT_USERNAME "GITHUB_USERNAME_VALUE"
setx GIT_TOKEN_KEY "GITHUB_TOKEN_KEY_VALUE"