spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: elastic-service-application

logging:
  level:
    root: info
#  file:
#    name: my-elastic.log
#  logback:
#    rollingpolicy:
#      max-file-size: 20MB