version: '3.1'

networks:
  default:
    driver: bridge

volumes:
  cache:
    driver: local

services:

# docker run -d -p 9411:9411 --name my-zipkin openzipkin/zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: my-zipkin
    ports:
      - "9411:9411"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 265M
        reservations:
          cpus: "0.25"
          memory: 128M

  #  docker run -d --hostname my-rabbit --name my-rabbitmq -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=123456789   -p 15672:15672  -p 5672:5672   --memory=128m   rabbitmq:3-management
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    hostname: my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123456789
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M




#  docker run --name my-redis -p 6379:6379 -d redis
#  docker run --name my-redis -p 6379:6379  --memory=128m  -d redis
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - '6379:6379'
