server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_PROJECT}
          default-label: main
          skip-ssl-validation: true
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN_KEY}


#spring:
#    profiles:
#      active: native
#    cloud:
#      config:
#        server:
#          native:
#            search-locations: classpath:/config-repo

