server:
  port: 80
  error:
    whitelabel:
      enabled: false

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: api-gateway
  cloud:
    gateway:
      default-filters:
        #        http://localhost/auth/findById/1
        #        /(?<segment>.*) :auth/findById/1
        #        /$\{segment} : bu kısım yakalanan segmenti uri'ye ekleyecek.
        #        http://localhost:9090/auth/findById/1
        - RewritePath= /(?<segment>.*), /$\{segment}
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallback/auth
        - id: product-service
          uri: http://localhost:9091
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: product
                fallbackUri: forward:/fallback/product
        - id: sale-service
          uri: http://localhost:9092
          predicates:
            - Path=/sale/**
          filters:
            - name: CircuitBreaker
              args:
                name: sale
                fallbackUri: forward:/fallback/sale
        - id: user-profile-service
          uri: http://localhost:9093
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fallback/user