server:
  port: 9100

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: elastic-service

authservice:
  secrets:
    key: ${JAVA_SECRETKEY}
    issuer: ${JAVA_ISSUER}
    exDate: 300000